### ISSUE TITLE
Summarize selected text on right click

### ISSUE THREAD

**Issue by Xaseron** [heavykenny/chrome-gemini-ext#1]
It would be nice to have the ability to summarize selected text on the right click menu. Is this possible and how hard is it to implement?
I have no clue about extension development.

**Comment by heavykenny** [comment]
Hi @Xaseron,

Thank you for reviewing the project and suggesting the feature. I will add this to the backlog and work on it.

Update: It's possible to add to this feature to the menu, the extention needs a bit of rework and should not take long. I will update you.

**Comment by heavykenny** [comment]
This is now available on v1.0.2 - It should be on Chrome Store in few days.
